-- Research-only Layer 10f backtest tables. Do not use for live Rocket/Crash.
CREATE TABLE IF NOT EXISTS rocket_backtest_events (
    event_id UUID PRIMARY KEY,
    symbol TEXT NOT NULL,
    session_date DATE NOT NULL,
    candle_time TIMESTAMPTZ NOT NULL,
    sess_bar_number INTEGER NOT NULL,
    score_long INTEGER NOT NULL,
    score_short INTEGER NOT NULL,
    dominant_side TEXT NOT NULL,
    s1 BOOLEAN NOT NULL,
    s2 BOOLEAN NOT NULL,
    s3 BOOLEAN NOT NULL,
    s4 BOOLEAN NOT NULL,
    bs1 BOOLEAN NOT NULL,
    bs2 BOOLEAN NOT NULL,
    bs3 BOOLEAN NOT NULL,
    bs4 BOOLEAN NOT NULL,
    close DOUBLE PRECISION,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    cum_delta_session DOUBLE PRECISION,
    delta_slope DOUBLE PRECISION,
    atr5 DOUBLE PRECISION,
    atr14 DOUBLE PRECISION,
    atr10 DOUBLE PRECISION,
    ema5 DOUBLE PRECISION,
    squeeze BOOLEAN NOT NULL,
    prior_quiet BOOLEAN NOT NULL,
    over_extended BOOLEAN NOT NULL,
    under_extended BOOLEAN NOT NULL,
    fwd_ret_1bar DOUBLE PRECISION,
    fwd_ret_3bar DOUBLE PRECISION,
    fwd_ret_5bar DOUBLE PRECISION,
    fwd_ret_10bar DOUBLE PRECISION,
    fwd_mfe_5bar DOUBLE PRECISION,
    fwd_mae_5bar DOUBLE PRECISION,
    fwd_direction_correct_1bar BOOLEAN,
    fwd_direction_correct_3bar BOOLEAN,
    adx_at_signal DOUBLE PRECISION,
    session_phase TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_rocket_bt_events_sym_dt
    ON rocket_backtest_events (symbol, session_date, candle_time);

CREATE TABLE IF NOT EXISTS rocket_backtest_summary (
    score_bucket INTEGER NOT NULL,
    side TEXT NOT NULL,
    session_phase TEXT NOT NULL,
    adx_bucket TEXT NOT NULL,
    squeeze BOOLEAN NOT NULL,
    signal_count INTEGER NOT NULL,
    win_rate_1bar DOUBLE PRECISION,
    win_rate_3bar DOUBLE PRECISION,
    win_rate_5bar DOUBLE PRECISION,
    avg_fwd_ret_3bar DOUBLE PRECISION,
    avg_mfe_5bar DOUBLE PRECISION,
    avg_mae_5bar DOUBLE PRECISION,
    avg_score_when_correct DOUBLE PRECISION,
    avg_score_when_wrong DOUBLE PRECISION,
    PRIMARY KEY (score_bucket, side, session_phase, adx_bucket, squeeze)
);
